version: "3.7"
services:
  docker:
    image: docker:dind
    user: root
    privileged: true
    container_name: jenkins-docker
    expose:
      - 2376
    volumes:
      - "jenkins-docker-certs:/certs/client"
      - "jenkins-data:/var/jenkins_home"
    networks:
      - jenkins
    environment:
      DOCKER_TLS_CERTDIR: "/certs"

  jenkins:
    image: alfred-thompson/jenkins-blueocean:2.332-1
    user: root
    container_name: jenkins-blueocean
    depends_on:
      - docker
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "jenkins-docker-certs:/certs/client:ro"
    networks:
      - jenkins
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT: "/certs/client"
      DOCKER_TLS_VERIFY: 1

  agent-alpine-jdk8:
    image: alfred-thompson/jenkins-ssh-agent:alpine-jdk8-1
    user: root
    container_name: agent-alpine-jdk8
    depends_on:
      - jenkins
    networks:
      - jenkins
    environment:
      JENKINS_AGENT_SSH_PUBKEY: "${SSH_PUBKEY}"

  agent-debian-jdk11:
    image: jenkins/ssh-agent:latest
    user: root
    container_name: agent-debian-jdk11
    depends_on:
      - jenkins
    networks:
      - jenkins
    environment:
      JENKINS_AGENT_SSH_PUBKEY: "${SSH_PUBKEY}"
    
  agent-alpine-maven:
    image: alfred-thompson/jenkins-ssh-agent:alpine-mvn
    user: root
    container_name: agent-alpine-maven
    depends_on:
      - jenkins
    networks:
      - jenkins
    environment:
      JENKINS_AGENT_SSH_PUBKEY: "${SSH_PUBKEY}"

  agent-debian-gcloud:
    image: alfred-thompson/jenkins-ssh-agent:gcloud
    user: root
    container_name: agent-debian-gcloud
    depends_on:
      - jenkins
    networks:
      - jenkins
    environment:
      JENKINS_AGENT_SSH_PUBKEY: "${SSH_PUBKEY}"

  mirror:
    image: nginx
    user: root
    container_name: mirror
    volumes:
      - "$PWD/nginx/volumes/nginx-cache:/var/cache/nginx"
      - "$PWD/nginx/volumes/nginx-pid:/var/run"
      - "$PWD/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "$PWD/nginx/www:/data/www"
      - "$PWD/nginx/dist:/data/dist"
    networks:
      - jenkins
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: "1"

volumes:
  jenkins-docker-certs:
  jenkins-data:

networks:
  jenkins:
    driver: bridge